/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#6f5673",
        "tertiary-fixed": "#e4e1e7",
        "primary-container": "#bc9ebf",
        "secondary-fixed-dim": "#d2c1da",
        "on-error": "#ffffff",
        "surface-container-low": "#f4f3f4",
        "on-tertiary-fixed-variant": "#47464b",
        "outline": "#7d747c",
        "secondary-container": "#e9d7f1",
        "primary-fixed": "#f9d8fb",
        "on-tertiary": "#ffffff",
        "tertiary": "#5f5e63",
        "on-tertiary-fixed": "#1b1b1f",
        "primary-fixed-dim": "#dcbcdf",
        "inverse-surface": "#2f3032",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e3e2e3",
        "surface-tint": "#6f5673",
        "outline-variant": "#cec3cc",
        "on-primary-fixed": "#28142d",
        "tertiary-fixed-dim": "#c8c5cb",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e3e2e3",
        "on-surface": "#1a1c1d",
        "on-secondary-container": "#6a5c72",
        "surface-dim": "#dadadb",
        "tertiary-container": "#a9a7ad",
        "surface": "#faf9fa",
        "secondary": "#67596f",
        "inverse-primary": "#dcbcdf",
        "on-tertiary-container": "#3d3c41",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f1f0f1",
        "error": "#ba1a1a",
        "surface-container-high": "#e9e8e9",
        "on-primary-fixed-variant": "#563e5b",
        "error-container": "#ffdad6",
        "on-primary-container": "#4c3550",
        "on-surface-variant": "#4c454b",
        "on-background": "#1a1c1d",
        "secondary-fixed": "#efdcf6",
        "surface-bright": "#faf9fa",
        "on-secondary-fixed": "#22172a",
        "background": "#faf9fa",
        "on-secondary": "#ffffff",
        "surface-container": "#eeedee",
        "on-secondary-fixed-variant": "#4f4257"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      borderRadius: {
        'xl': '1.5rem',
      }
    },
  },
  plugins: [],
}
